import React, { useState, useEffect } from 'react';
import { generateQuiz } from '../services/geminiService';
import { QuizQuestion } from '../types';
import { X, CheckCircle, AlertCircle, Loader2 } from 'lucide-react';

interface QuizModalProps {
  isOpen: boolean;
  onClose: () => void;
  articleContent: string;
}

const QuizModal: React.FC<QuizModalProps> = ({ isOpen, onClose, articleContent }) => {
  const [question, setQuestion] = useState<QuizQuestion | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setLoading(true);
      setQuestion(null);
      setSelectedOption(null);
      setIsSubmitted(false);

      generateQuiz(articleContent).then((q) => {
        setQuestion(q);
        setLoading(false);
      });
    }
  }, [isOpen, articleContent]);

  if (!isOpen) return null;

  const handleOptionSelect = (index: number) => {
    if (!isSubmitted) {
        setSelectedOption(index);
    }
  };

  const handleSubmit = () => {
    if (selectedOption !== null) {
        setIsSubmitted(true);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/70 backdrop-blur-sm fade-in">
      <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full relative overflow-hidden">
        
        <button 
            onClick={onClose}
            className="absolute top-4 right-4 text-slate-400 hover:text-slate-600 transition-colors p-1"
        >
            <X className="w-6 h-6" />
        </button>

        <div className="p-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-2">Smart Quiz</h2>
            <p className="text-slate-500 text-sm mb-6">Generated by AI based on the article.</p>

            {loading ? (
                <div className="flex flex-col items-center justify-center py-12 gap-3 text-slate-500">
                    <Loader2 className="w-10 h-10 animate-spin text-indigo-600" />
                    <p>Crafting a challenge for you...</p>
                </div>
            ) : question ? (
                <div>
                    <p className="text-lg font-medium text-slate-800 mb-6">{question.question}</p>
                    
                    <div className="space-y-3 mb-8">
                        {question.options.map((option, idx) => {
                            let itemClass = "w-full text-left p-4 rounded-xl border-2 transition-all flex items-center justify-between ";
                            
                            if (isSubmitted) {
                                if (idx === question.correctAnswerIndex) {
                                    itemClass += "border-green-500 bg-green-50 text-green-900";
                                } else if (idx === selectedOption) {
                                    itemClass += "border-red-500 bg-red-50 text-red-900";
                                } else {
                                    itemClass += "border-slate-100 opacity-50";
                                }
                            } else {
                                if (selectedOption === idx) {
                                    itemClass += "border-indigo-600 bg-indigo-50 text-indigo-900";
                                } else {
                                    itemClass += "border-slate-100 hover:border-indigo-200 hover:bg-slate-50";
                                }
                            }

                            return (
                                <button
                                    key={idx}
                                    onClick={() => handleOptionSelect(idx)}
                                    disabled={isSubmitted}
                                    className={itemClass}
                                >
                                    <span>{option}</span>
                                    {isSubmitted && idx === question.correctAnswerIndex && <CheckCircle className="w-5 h-5 text-green-600" />}
                                    {isSubmitted && idx === selectedOption && idx !== question.correctAnswerIndex && <AlertCircle className="w-5 h-5 text-red-600" />}
                                </button>
                            );
                        })}
                    </div>

                    {!isSubmitted ? (
                        <button
                            onClick={handleSubmit}
                            disabled={selectedOption === null}
                            className={`w-full py-3 rounded-lg font-bold text-white transition-all ${
                                selectedOption !== null 
                                ? 'bg-indigo-600 hover:bg-indigo-700 shadow-lg hover:shadow-indigo-500/30' 
                                : 'bg-slate-300 cursor-not-allowed'
                            }`}
                        >
                            Submit Answer
                        </button>
                    ) : (
                        <div className={`p-4 rounded-lg text-sm leading-relaxed ${
                            selectedOption === question.correctAnswerIndex 
                            ? 'bg-green-100 text-green-800' 
                            : 'bg-indigo-50 text-indigo-800'
                        }`}>
                            <span className="font-bold block mb-1">
                                {selectedOption === question.correctAnswerIndex ? 'Correct!' : 'Explanation:'}
                            </span>
                            {question.explanation}
                        </div>
                    )}
                </div>
            ) : (
                <div className="text-center text-red-500">
                    Failed to generate quiz. Please try again.
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default QuizModal;